<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Robot Dimensions -->
  <xacro:property name="base_length" value="0.3" />
  <xacro:property name="base_width" value="0.25" />
  <xacro:property name="base_height" value="0.1" />
  <xacro:property name="base_mass" value="2.5" />
  
  <!-- Wheel Properties -->
  <xacro:property name="wheel_radius" value="0.05" />
  <xacro:property name="wheel_width" value="0.04" />
  <xacro:property name="wheel_mass" value="0.3" />
  <xacro:property name="wheel_offset_x" value="${base_length/4}" />
  <xacro:property name="wheel_offset_y" value="${base_width/2 + wheel_width/4}" />
  <xacro:property name="wheel_offset_z" value="-${base_height/2}" />
  
  <!-- Caster Properties (if needed) -->
  <xacro:property name="caster_radius" value="0.02" />
  <xacro:property name="caster_mass" value="0.1" />
  
  <!-- Sensor Properties -->
  <xacro:property name="lidar_size" value="0.05" />
  <xacro:property name="lidar_mass" value="0.1" />
  <xacro:property name="lidar_height" value="0.1" />
  
  <!-- IMU Properties -->
  <xacro:property name="imu_size" value="0.02" />
  <xacro:property name="imu_mass" value="0.01" />
  
  <!-- Joint Properties -->
  <xacro:property name="wheel_joint_damping" value="0.1" />
  <xacro:property name="wheel_joint_friction" value="0.1" />
  
  <!-- Colors -->
  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>
  
  <material name="blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>
  
  <material name="green">
    <color rgba="0.0 0.8 0.0 1.0"/>
  </material>
  
  <material name="grey">
    <color rgba="0.2 0.2 0.2 1.0"/>
  </material>
  
  <material name="orange">
    <color rgba="1.0 0.423529411765 0.0392156862745 1.0"/>
  </material>
  
  <material name="brown">
    <color rgba="0.870588235294 0.811764705882 0.764705882353 1.0"/>
  </material>
  
  <material name="red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>
  
  <material name="white">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>
</robot>
