<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Wheel Macro -->
  <xacro:macro name="wheel" params="name x_offset y_offset z_offset flip">
    <link name="${name}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}" />
        </geometry>
        <material name="grey" />
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}" />
        </geometry>
      </collision>
      
      <inertial>
        <mass value="${wheel_mass}" />
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <inertia 
          ixx="${wheel_mass * (3 * wheel_radius * wheel_radius + wheel_width * wheel_width) / 12}"
          iyy="${wheel_mass * (3 * wheel_radius * wheel_radius + wheel_width * wheel_width) / 12}"
          izz="${wheel_mass * wheel_radius * wheel_radius / 2}"
          ixy="0.0" iyz="0.0" ixz="0.0" />
      </inertial>
    </link>
    
    <joint name="${name}_wheel_joint" type="continuous">
      <parent link="base_link" />
      <child link="${name}_wheel_link" />
      <origin xyz="${x_offset} ${y_offset * flip} ${z_offset}" rpy="0 0 0" />
      <axis xyz="0 1 0" />
      <dynamics damping="${wheel_joint_damping}" friction="${wheel_joint_friction}" />
    </joint>
    

  </xacro:macro>
</robot>
